### ISSUE TITLE
armhf exec format error

### ISSUE THREAD

**Issue by ChaosMarc** [organizrTools/docker-organizr-v2#6]
Since the latest commit a1c3430b4bc095d3d8849ed8e777eea6e5fcb80b the armhf and dev-armhf cannot be started anymore due to an exec format error.

```
# uname -a
Linux odroid 4.14.47-132 #1 SMP PREEMPT Sun Jun 3 22:33:16 UTC 2018 armv7l armv7l armv7l GNU/Linux
```

```
        organizr:
                container_name: organizr
                restart: unless-stopped
                volumes:
                        - '/mnt/sd/docker/config/organizr:/config'
                ports:
                        - '82:80'
                image: organizrtools/organizr-v2:armhf
```

```
# docker-compose logs -f organizr
Attaching to organizr
organizr        | standard_init_linux.go:190: exec user process caused "exec format error"
organizr        | standard_init_linux.go:190: exec user process caused "exec format error"
organizr        | standard_init_linux.go:190: exec user process caused "exec format error"
organizr        | standard_init_linux.go:190: exec user process caused "exec format error"
organizr        | standard_init_linux.go:190: exec user process caused "exec format error"
organizr        | standard_init_linux.go:190: exec user process caused "exec format error"
organizr        | standard_init_linux.go:190: exec user process caused "exec format error"
organizr        | standard_init_linux.go:190: exec user process caused "exec format error"
organizr exited with code 1
```
